/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardCompanyIdRouteImport } from './routes/dashboard/$companyId'
import { Route as DevPreviewRouteImport } from './routes/dev/preview'
import { Route as ExperiencesExperienceIdRouteImport } from './routes/experiences/$experienceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompanyIdRoute = DashboardCompanyIdRouteImport.update({
  id: '/dashboard/$companyId',
  path: '/dashboard/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPreviewRoute = DevPreviewRouteImport.update({
  id: '/dev/preview',
  path: '/dev/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesExperienceIdRoute = ExperiencesExperienceIdRouteImport.update({
  id: '/experiences/$experienceId',
  path: '/experiences/$experienceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdRoute
  '/dev/preview': typeof DevPreviewRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdRoute
  '/dev/preview': typeof DevPreviewRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdRoute
  '/dev/preview': typeof DevPreviewRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/dashboard/$companyId'
    | '/dev/preview'
    | '/experiences/$experienceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/dashboard/$companyId'
    | '/dev/preview'
    | '/experiences/$experienceId'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/dashboard/$companyId'
    | '/dev/preview'
    | '/experiences/$experienceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  DashboardCompanyIdRoute: typeof DashboardCompanyIdRoute
  DevPreviewRoute: typeof DevPreviewRoute
  ExperiencesExperienceIdRoute: typeof ExperiencesExperienceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$companyId': {
      id: '/dashboard/$companyId'
      path: '/dashboard/$companyId'
      fullPath: '/dashboard/$companyId'
      preLoaderRoute: typeof DashboardCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/preview': {
      id: '/dev/preview'
      path: '/dev/preview'
      fullPath: '/dev/preview'
      preLoaderRoute: typeof DevPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$experienceId': {
      id: '/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof ExperiencesExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  DashboardCompanyIdRoute: DashboardCompanyIdRoute,
  DevPreviewRoute: DevPreviewRoute,
  ExperiencesExperienceIdRoute: ExperiencesExperienceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
